version: '3.6'

services:
  findmystarbucks.client:
    container_name: findmystarbucks.client
    build: ../client
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    image: findmystarbucks.client:${VERSION}

  findmystarbucks.api:
    container_name: findmystarbucks.api
    build: ../kostack
    ports: 
      - "${API_PORT}:${API_PORT}"
    image: findmystarbucks.api:${VERSION}